# Site settings
author: sensible-partial-6157
title: 
header-img: img/home-bg.png
email: daniyellaharmon@gmail.com
copyright_name: sensible-partial-6157
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  daniyellalove

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
